# Домашнее задание №2, Козарев М.Ю. РИ-450005

## Основы исследовательского анализа данных.

## Исходные данные

По адресу https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv можно получить набор данных, содержащий информацию о домовладениях в Калифорнии и Пенсильвании за 2011г. Информация сгруппированна по зонам переписи (Census tracts).

## Загрузка и очистка данных

1. Загрузите данные в датафрейм, который назовите data.

```
> data <- data.frame(read.csv("https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv"))
```

2. Сколько строк и столбцов в data?

```
> nrow(data)
[1] 11275
> ncol(data)
[1] 34
```

3. Выполните следующую команду и объясните, что она делает. colSums(apply(data,c(1,2), is.na))

```
> colSums(apply(data,c(1,2), is.na))
                          X                     GEO.id2 
                          0                           0 
                    STATEFP                    COUNTYFP 
                          0                           0 
                    TRACTCE                  POPULATION 
                          0                           0 
                   LATITUDE                   LONGITUDE 
                          0                           0 
          GEO.display.label          Median_house_value 
                          0                         599 
                Total_units                Vacant_units 
                          0                           0 
               Median_rooms  Mean_household_size_owners 
                        157                         215 
Mean_household_size_renters         Built_2005_or_later 
                        152                          98 
         Built_2000_to_2004                 Built_1990s 
                         98                          98 
                Built_1980s                 Built_1970s 
                         98                          98 
                Built_1960s                 Built_1950s 
                         98                          98 
                Built_1940s       Built_1939_or_earlier 
                         98                          98 
                 Bedrooms_0                  Bedrooms_1 
                         98                          98 
                 Bedrooms_2                  Bedrooms_3 
                         98                          98 
                 Bedrooms_4          Bedrooms_5_or_more 
                         98                          98 
                     Owners                     Renters 
                        100                         100 
    Median_household_income       Mean_household_income 
                        115                         126 
```

4. Функция na.omit() принимает датафрейм и возвращает новый датафрейм, игнорируя строки, содержащие значение NA. Используйте эту функцию для удаления строк с неполными данными.
5. Сколько строк было удалено?

```
> dataFixed <- na.omit(data)
> nrow(data)-nrow(dataFixed)
[1] 670
```

### Было удалено 670 строк

6. Соответствует ли результат выполнения, значениям из пункта 3?

```
> colSums(apply(dataFixed,c(1,2), is.na))
                          X                     GEO.id2 
                          0                           0 
                    STATEFP                    COUNTYFP 
                          0                           0 
                    TRACTCE                  POPULATION 
                          0                           0 
                   LATITUDE                   LONGITUDE 
                          0                           0 
          GEO.display.label          Median_house_value 
                          0                           0 
                Total_units                Vacant_units 
                          0                           0 
               Median_rooms  Mean_household_size_owners 
                          0                           0 
Mean_household_size_renters         Built_2005_or_later 
                          0                           0 
         Built_2000_to_2004                 Built_1990s 
                          0                           0 
                Built_1980s                 Built_1970s 
                          0                           0 
                Built_1960s                 Built_1950s 
                          0                           0 
                Built_1940s       Built_1939_or_earlier 
                          0                           0 
                 Bedrooms_0                  Bedrooms_1 
                          0                           0 
                 Bedrooms_2                  Bedrooms_3 
                          0                           0 
                 Bedrooms_4          Bedrooms_5_or_more 
                          0                           0 
                     Owners                     Renters 
                          0                           0 
    Median_household_income       Mean_household_income 
                          0                           0 
```

### Нет, т.к. Na элементы были удалены.

## Новые дома

1. Переменная(колонка) Built_2005_or_later содержит данные о проценте домов, построенных с 2005 года. Постройте диаграмму рассеяния (scatterplot) медианы стоимости домов (переменная Median_house_value) относительно процента новых домов.

```
> scatter.smooth(data$Built_2005_or_later, data$Median_house_value)
```

2. Постройте ещё два графика для каждого из штатов отдельно. Номер штата содержится в переменной (STATEFP), где Калифорния 6-й штат, а Пенсильвания 42.

```
> scatter.smooth(data$Built_2005_or_later[data$STATEFP==6], data$Median_house_value[data$STATEFP==6])
> scatter.smooth(data$Built_2005_or_later[data$STATEFP==42], data$Median_house_value[data$STATEFP==42])
```

## Незанятые дома

Уровень найма (vacancy rate) — доля домов, которые не были заняты. В данных содержатся колонки, содержащие общее количество домовладений и количество не занятых домовладений.

1. В датафрейм data добавьте новую колонку vacancy_rate, которая должна содержать вышеописанный показатель.

```
> data$vacancy_rate <- data$Vacant_units / data$Total_units
```

2. Найдите минимум, максимум, среднее и медиану полученных значений показателя.

```
> vacancyRate <- na.omit(data$vacancy_rate)
> min(vacancyRate)
[1] 0
> max(vacancyRate)
[1] 1
> median(vacancyRate)
[1] 0.06766326
> mean(vacancyRate)
[1] 0.08917878
```

3. Постройте диаграмму уровня найма относительно медианы стоимости домов. Что можно заметить?

```
> plot(data$Median_house_value, data$vacancy_rate)
```

### Больший найм у более дешевых домов.

# Корреляция 

Колонка COUNTYFP содержит числовой код округа внутри штата. Нас интересуют Butte County (округ 7 в Калифорнии), Santa Clara (округ 85 в Калифорнии) и York County (округ 133 в Пенсильвании).

1. Объясните, что делает приведённый в конце задания код и как именно он это делает.

```
> acc <- c()
> for (tract in 1:nrow(data)) {
+     if (data$STATEFP[tract] == 6) {
+         if (data$COUNTYFP[tract] == 1) {
+             acc <- c(acc, tract)
+         }
+     }
+ }
> accmv <- c()
> for (tract in acc) {
+     accmv <- c(accmv, data[tract,10])
+ }
> median(accmv)
[1] 474050
```

### Добавляем в переменную acc номера строк с номером штата 6 и номером округа 1. Затем в переменную accmv записываем значение колонки Median_house_value по строчкам acc и в конце считаем медиану accmv

2. Напишите другим способом в одну строку, то же самое, что делает нижеуказанный код. Способов получить тот же ответ множество, достаточно одного.

```
> median(data$Median_house_value[data$STATEFP==6][data$COUNTYFP==1], na.rm=TRUE)
[1] 474050
```

3. Найдите средний процент построенных домовладений в округах (Butte County, Santa Clara, York County)

```
> perButte <- mean(data$Total_units[data$STATEFP==6&data$COUNTYFP==7]/sum(data$Total_units[data$STATEFP==6]))
> perButte
[1] 0.0001458294
> perSanta <- mean(data$Total_units[data$STATEFP==6&data$COUNTYFP==85]/sum(data$Total_units[data$STATEFP==6]))
> perSanta
[1] 0.0001320997
> perYork <- mean(data$Total_units[data$STATEFP==42&data$COUNTYFP==133]/sum(data$Total_units[data$STATEFP==42]))
> perYork
[1] 0.000360114
```

4. Функция cor рассчитывает коэффициент корреляции между двумя переменными. Рассчитайте корреляцию между медианы стоимости домовладений (Median_house_value) и процентом построенных домов (Built_2005_or_later):

i. для всего набора данных

```
> cor(as.numeric(data$Built_2005_or_later), data$Median_house_value)
[1] -0.01893186
```

ii. для Калифорнии

```
> cor(as.numeric(data$Built_2005_or_later[data$STATEFP==6]), data$Median_house_value[data$STATEFP==6])
[1] -0.1153604
```

iii. для Пенсильвании

```
> cor(as.numeric(data$Built_2005_or_later[data$STATEFP==42]), data$Median_house_value[data$STATEFP==42])
[1] 0.2681654
```
iv. для округа Butte County

```
> cor(as.numeric(data$Built_2005_or_later[data$STATEFP==6&data$COUNTYFP==7]), data$Median_house_value[data$STATEFP==6&data$COUNTYFP==7])
[1] 0.04203267
```

v. для округа Santa Clara

```
> cor(as.numeric(data$Built_2005_or_later[data$STATEFP==6&data$COUNTYFP==85]), data$Median_house_value[data$STATEFP==6&data$COUNTYFP==85])
[1] -0.1726203
```

v. для округа York County

```
> cor(as.numeric(data$Built_2005_or_later[data$STATEFP==42&data$COUNTYFP==133]), data$Median_house_value[data$STATEFP==42&data$COUNTYFP==133])
[1] 0.3860773
```

5. Постройте три диаграммы медианы стоимости домовладений (Median_house_value) относительно медианы дохода (Median_household_income) для трёх округов. Допустимо указать все три на одном графике.

```
> plot(data$Median_house_value[data$STATEFP==6&data$COUNTYFP==7], data$Median_household_income[data$STATEFP==6&data$COUNTYFP==7])
> plot(data$Median_house_value[data$STATEFP==6&data$COUNTYFP==85], data$Median_household_income[data$STATEFP==6&data$COUNTYFP==85])
> plot(data$Median_house_value[data$STATEFP==42&data$COUNTYFP==133], data$Median_household_income[data$STATEFP==42&data$COUNTYFP==133])
```